name: Deploy Automatico via FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Baixar codigo fonte
        uses: actions/checkout@v4

      - name: Instalar Node e compilar o site
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run build

      - name: Enviar arquivos para a HostGator via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ./
